name: Recovery Build Final

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maximize Disk Space
        run: |
          # GitHub Runner-ын хэрэггүй бүх зүйлийг устгаж 30GB+ зай гаргах
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/boost /usr/local/openjdk* /usr/local/share/powershell /usr/local/share/chromium
          sudo apt-get clean
          sudo docker image prune -a -f
          df -h

      - name: Install Build Tools
        run: |
          sudo apt update
          sudo apt install -y bc build-essential curl git gperf gcc-multilib g++-multilib \
          lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 \
          libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush \
          rsync schedtool squashfs-tools xsltproc zip zlib1g-dev \
          python3 python-is-python3 imagemagick libtinfo5

      - name: Set up Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Actions"
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Sync TWRP Source
        run: |
          mkdir -p ~/twrp && cd ~/twrp
          # Depth=1 ашиглаж түүх татахгүйгээр зай хэмнэнэ
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-14.1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --depth=1
          
          # Linux build-д хэрэггүй Darwin (Mac) болон Windows-ийн том файлуудыг устгах
          rm -rf prebuilts/clang/host/darwin-x86
          rm -rf prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8
          rm -rf .repo/projects
          df -h

      - name: Clone Device Tree
        run: |
          cd ~/twrp
          git clone https://github.com/Cosmic802/A716s-UNOFFICAL-TWRP device/samsung/a716s

      - name: Build TWRP
        run: |
          cd ~/twrp
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          # Төхөөрөмжийн тохиргоог идэвхжүүлэх
          lunch twrp_a716s-eng || lunch omni_a716s-eng
          # Compile хийх процесс (Хамгийн их цаг авна)
          mka recoveryimage -j$(nproc --all)

      - name: Upload Result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-A716S-Final-Image
          path: /home/runner/twrp/out/target/product/a716s/*.img
